name: demo 

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello World"
      - uses: actions/checkout@main
      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - uses: azure/docker-login@v1
        with:
          login-server: menunovation.azurecr.io  # Registery
          # username: ${{ secrets.REGISTRY_USERNAME }}
          # password: ${{ secrets.REGISTRY_PASSWORD }}
          username: 35d88912-c05a-429c-a775-65f4eb81ff40
          password: jfIcaILv7RclqDOO-c.JDd68mze7pnv77J
      - run: docker build . -t menunovation.azurecr.io/demo
      - run: docker push menunovation.azurecr.io/demo